import type { Command } from "./types.js";

const elements = new Set([
  "hydrogen",
  "helium",
  "lithium",
  "beryllium",
  "boron",
  "carbon",
  "nitrogen",
  "oxygen",
  "fluorine",
  "neon",
  "sodium",
  "magnesium",
  "aluminum",
  "aluminium",
  "silicon",
  "phosphorus",
  "sulfur",
  "chlorine",
  "argon",
  "potassium",
  "calcium",
  "scandium",
  "titanium",
  "vanadium",
  "chromium",
  "manganese",
  "iron",
  "cobalt",
  "nickel",
  "copper",
  "zinc",
  "gallium",
  "germanium",
  "arsenic",
  "selenium",
  "bromine",
  "krypton",
  "rubidium",
  "strontium",
  "yttrium",
  "zirconium",
  "niobium",
  "molybdenum",
  "technetium",
  "ruthenium",
  "rhodium",
  "palladium",
  "gold",
  "silver",
  "cadmium",
  "indium",
  "tin",
  "antimony",
  "tellurium",
  "iodine",
  "xenon",
  "cesium",
  "barium",
  "lanthanum",
  "cerium",
  "praseodymium",
  "neodymium",
  "promethium",
  "samarium",
  "europium",
  "gadolinium",
  "terbium",
  "dysprosium",
  "holmium",
  "erbium",
  "thulium",
  "ytterbium",
  "lutetium",
  "hafnium",
  "tantalum",
  "tungsten",
  "rhenium",
  "osmium",
  "iridium",
  "platinum",
  "mercury",
  "thallium",
  "lead",
  "bismuth",
  "polonium",
  "astatine",
  "radon",
  "francium",
  "radium",
  "actinium",
  "thorium",
  "protactinium",
  "uranium",
  "neptunium",
  "plutonium",
  "americium",
  "curium",
  "berkelium",
  "californium",
  "einsteinium",
  "fermium",
  "mendelevium",
  "nobelium",
  "lawrencium",
  "rutherfordium",
  "dubnium",
  "seaborgium",
  "bohrium",
  "hassium",
  "meitnerium",
  "darmstadtium",
  "roentgenium",
  "copernicium",
  "ununtrium",
  "flerovium",
  "ununpentium",
  "livermorium",
  "ununseptium",
  "ununoctium",
]);

export const snarkCommands: Command[] = [
  {
    name: "make",
    description: "A legacy Banjo retort.",
    category: "snarks",
    execute: () => "Make it yourself.",
  },
  {
    name: "sudo",
    description: "A legacy Banjo retort.",
    category: "snarks",
    execute: () => "Ok.",
  },
  {
    name: "donut",
    description: "A legacy Banjo snack.",
    category: "snarks",
    execute: () => "*Yummeh*",
  },
  {
    name: "suicide",
    description: "Show the legacy support hotline response.",
    category: "snarks",
    execute: () => "National Suicide Prevention Lifeline: `1-800-273-8255`",
  },
  {
    name: "roll",
    description: "Roll a fair legacy die.",
    usage: "roll",
    category: "snarks",
    execute: () =>
      "Your random number is: **4** - chosen by fair dice roll, guaranteed to be random, see RFC 1149.5.",
  },
  {
    name: "lmgtfy",
    description: "Build a Let Me Google That For You query.",
    usage: "lmgtfy <query>",
    category: "snarks",
    execute: (_context, args) => `https://lmgtfy.com/?q=${args.join(" ")}`,
  },
  {
    name: "ricky!",
    description: "Send the legacy Ricky image.",
    category: "snarks",
    execute: () => "https://raw.githubusercontent.com/inertia186/banjo_bot/master/support/images/ricky.gif",
  },
  {
    name: "kappa",
    description: "Send the legacy Kappa image.",
    category: "snarks",
    execute: () => "https://raw.githubusercontent.com/inertia186/banjo_bot/master/support/images/kappa.png",
  },
  {
    name: "hydrogen",
    aliases: [...elements].filter((name) => name !== "hydrogen"),
    description: "Run the legacy element lookup.",
    usage: "<element>",
    category: "snarks",
    execute: ({ commandName, config }) =>
      `\`${config.commandPrefix}${commandName}\` is a Wolfram Alpha-backed legacy lookup and has not been ported yet.`,
  },
];
